format_version: 10
pipelines:
  Progress1:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c30ee0e:
        git: https://github.com/zouxifeng/gocd.git
        shallow_clone: false
        auto_update: false
        branch: master
    stages:
    - Stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Packaging:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Packaging
                command: echo
                run_if: passed
