format_version: 10
environments:
  Stage:
    pipelines:
      - Progress
pipelines:
  Progress:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c30ee0e:
        git: git@172.16.3.45:gocd-test.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Testing:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          UnitTest:
            timeout: 0
            tasks:
            - init:
                arguments:
                - install
                - tox
                command: pip3
                run_if: passed
            - exec:
                command: tox
                run_if: passed
    - DeploySandbox:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          BuildAritfact:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Building Artifact
                command: echo
                run_if: passed
