format_version: 10
environments:
  Stage:
    pipelines:
      - Progress
pipelines:
  Progress:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c30ee0e:
        git: https://github.com/zouxifeng/gocd.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Testing:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Packaging:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Packaging
                command: echo
                run_if: passed
    - DeploySandbox:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          BuildAritfact:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Building Artifact
                command: echo
                run_if: passed
